[package]
name = "blockchain-client"
version = "0.1.0"
authors = ["Andrew Fister <temposs@gmail.com>"]

[dependencies]

argparse = "*"
zmq = "0.8"

[dependencies.yaml-rust]
git = "https://github.com/chyh1990/yaml-rust.git"